### ISSUE TITLE
Navigation Header UI Updates

### ISSUE THREAD

**Issue by JosueBrenes** [safetrustcr/Frontend#109]
## Description
Updates needed for the header component to simplify the UI and modify several elements.

## Changes Required
1. Search Bar
   - Update search bar styling (awaiting image reference for specific design)
   - Replace current search icon with React Icons component

2. Language Selector
   - Remove flag icons
   - Display only language initials
   - Keep only:
     - EN (English)
     - ES (Spanish)

3. Logo
   - Remove text from logo
   - Keep only the logo symbol

## Technical Notes
- Use React Icons library for the search icon implementation
- Ensure responsive design is maintained after updates
- Maintain existing functionality while updating the UI

## Acceptance Criteria
- [ ] Search bar matches provided design reference
- [ ] Search icon is updated using React Icons
- [ ] Language selector shows only "EN" and "ES" without flags
- [ ] Logo displays only the symbol without text
- [ ] All functionality remains working as expected
- [ ] UI is responsive across all breakpoints

## Additional Information
Please provide the reference image for the search bar design to ensure accurate implementation

![Image](https://github.com/user-attachments/assets/11139b50-4402-4156-a9a1-cecdb8205d1c)

**Comment by Shoetan** [comment]
Could I take over this issue?I am Emmanuel returning contributor skilled in React,Tailwind CSS, TypeScript, Cairo and Redux, with experience contributing to open-source projects on only dust
 Recently contributed to Carbonable PR: https://github.com/Carbonable/contracts-watcher/pull/27   I’ll address this issue by delivering clean, efficient, and well-documented code.  Onlydust Profile: https://app.onlydust.com/u/Shoetan

**Comment by KevinLatino** [comment]
Hello My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base. I've also contributed to projects in ecosystems like Starknet and Stellar.

I’ll update the search bar styling, replace the icon with a React Icon, adjust the language selector to show "EN" and "ES" only, and modify the logo to display the symbol only, ensuring functionality and responsiveness remain intact.

**Comment by josephchimebuka** [comment]
Can I try solving this issue?

**Comment by khayss** [comment]
Can I work on this, please?

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I'm a fullstack and blockchain developer with experience this field for more than 1.5 years and had worked on previous session of odhack my profile:(https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Michaelkingsdev** [comment]
May I try my hand at this?

**Comment by emmz3230** [comment]
I am a front-end web developer with skills like HTML, CSS, JavaScript, React.js, and Next.js.
I have experience writing code for websites and web apps.
I will use the React icon by installing the React icon if not installed and import it for use in the code by referencing the search bar design to ensure accurate implementation.
I will also make sure i maiantain existing functionality.
thanks. will love to contribute to this project

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by Cisco-A** [comment]
Could I take over this issue?

**Comment by starknetbrother** [comment]
May I be assigned to this?
