### ISSUE TITLE
Moving Bids to Profile Directory

### ISSUE THREAD

**Issue by JosueBrenes** [safetrustcr/Frontend#112]
Moving Bids to Profile Directory

## Description

Reorganize bid-related files into a new directory under the profile, update import paths and routes, and test functionality to ensure no broken links or errors. A backup of the original directory will be kept until changes are verified in production.

## Current Structure

```
app/
├── bids/
│   └── [bid files and components]
└── profile/
    └── [profile files and components]
```

### 1. File Movement
- Move all contents from app/bids/ to app/profile/bids/

### 2. Directory Structure Update

```
app/
└── profile/
    ├── existing-profile-files/
    └── bids/
        └── [migrated bid files and components]
```

#### Files to Update
- Update import statements in all files that reference the bids directory
- Update routing configurations
- Update any API endpoints that reference bid paths

#### Path Updates Required

```
Old path: app/bids/*
New path: app/profile/bids/*
```

### 4. Verification Checklist
- [ ] Create new bids directory under profile
- [ ] Move all bid-related files to new location
- [ ] Update import paths in all related files
- [ ] Update routing configuration
- [ ] Test all bid-related functionality
- [ ] Verify profile navigation still works
- [ ] Clean up old bids directory

### 5. Testing Steps
1. Verify bid components render correctly in new location
2. Test all bid-related functionality
3. Ensure profile navigation works with new structure
4. Confirm no broken links or 404 errors
5. Test user flow through bid-related features

## Rollback Plan
Keep backup of original bids directory until changes are verified in production.

**Comment by mimisavage** [comment]
Can I work on this, please?

**Comment by KevinLatino** [comment]
Hello My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base. I've also contributed to projects in ecosystems like Starknet and Stellar.

I will move all bid-related files from app/bids/ to app/profile/bids/ and update the import paths, routing configurations, and any API endpoints referencing the old bid paths. I’ll ensure all links are correct, test functionality to avoid errors

**Comment by josephchimebuka** [comment]
I'd like to take this issue.

**Comment by raizo07** [comment]
Can I jump on this task? I'm a Software developer with over 3 years experience

**Comment by Michaelkingsdev** [comment]
Could I grab this task?

**Comment by A6dulmalik** [comment]
Mind if I take this issue? I am a new contributor ready to contribute to this issue.

**Comment by KevinMB0220** [comment]
Hi, I'm Kevin, I'm part of Dojo Coding, I have experience working in web development, I've participated in different projects, also in open source collaborations, so I would follow the design instructions and do it in the best way.

**Comment by kayceeDev** [comment]
Is it okay if I take this?

**Comment by kallis312** [comment]
Can I tackle this one?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by kendel-amador** [comment]
# 📝 **Proposal for the Issue: "Move the bids folder to profile/bids"**  

## 👤 **Personal Introduction**  
Hi, I’m Kendel Amador, a frontend developer with a strong interest in creating intuitive and engaging web experiences. I specialize in using React to build responsive, interactive applications. Although I’m new to contributing to open-source projects, I’m excited to expand my skills, collaborate with others, and contribute to meaningful codebases.

---

## 💡 **Solution Proposal**  
I would like to work on the issue **"Move the bids folder to profile/bids"**. Here’s my proposed plan to complete the task efficiently and in an organized way:  

### 1️⃣ **File Reorganization**  
- Create the new folder `app/profile/bids/`.  
- Move all bid-related files to this new location.  

### 2️⃣ **Updating Imports and Routes**  
- Search for and update all import statements referencing `app/bids/...` to `app/profile/bids/...`.  
- Update route configurations and API endpoints as needed.  

### 3️⃣ **Testing and Verification**  
- Ensure that all **bids** components render correctly.  
- Verify that navigation between sections works without errors.  
- Check for broken links or 404 errors.  

### 4️⃣ **Rollback Plan**  
- Keep a backup of the original structure until the changes are properly verified.  

---

## 🌟 **Benefits**  
- **Clean Structure:** Improved organization and consistency in the project’s architecture.  
- **Easier Maintenance:** Clearer and more maintainable imports and routes.  

---

**I'm excited to make my first open-source contribution, and I'm looking forward to learning and collaborating on this project!** 😄😄😄😄

**Comment by TheSQLguy** [comment]
Hey, I am new to open-source
To address this issue, I would move all bid-related files from app/bids/ to app/profile/bids/ and update the necessary import paths, routing configurations, and API endpoints to reflect the new directory structure. Verify that bid components render correctly, profile navigation remains functional, and there are no broken links or errors. Keep a backup of the original directory until production verification is complete.

**Comment by ikezuby2012** [comment]
I’d love to work on this task.
