### ISSUE TITLE
Profile Navigation Enhancement

### ISSUE THREAD

**Issue by zleypner** [safetrustcr/Frontend#116]
# Profile Navigation Enhancement

## Description
Implement navigation buttons and views in the profile section to improve user access to apartments and offers.

### 1. Profile Navigation Button
- Create a button that redirects to the main profile page
- Target URL: http://localhost:3000/profile
- Button should be clearly visible and accessible from relevant pages
- Include appropriate styling consistent with existing UI

![Image](https://github.com/user-attachments/assets/4d773935-2f05-409f-b670-6aecc5029f1c)

### 2. My Apartments View
- Improve the current view for the path 
- Target URL: http://localhost:3000/profile/my-apartments
- Implement route handling in the router
- Create necessary components for displaying apartment listings
- Include proper layout and styling

### 3. Interested People View
- Improve the current view for the path
- Target URL: http://localhost:3000/profile/interested-people
- Implement route handling in the router
- Create components to display interested users/offers
- Include proper layout and styling

## Technical Requirements
- Implement using React Router for navigation
- Ensure proper state management
- Add error handling for invalid routes
- Include loading states
- Make components responsive

## Acceptance Criteria
- [ ] Main profile button redirects successfully to /profile
- [ ] My Apartments view is accessible at /profile/my-apartments
- [ ] Interested People view is accessible at /profile/interested-people
- [ ] All routes are properly protected with authentication
- [ ] Navigation is smooth with no page refreshes
- [ ] UI is consistent with existing design system
- [ ] All views are responsive on mobile devices

## Additional Notes
- Consider adding breadcrumb navigation
- Include loading states for data fetching
- Add proper error boundaries
- Consider adding animations for transitions

## Resources
-Keep the projects structure
- Design system documentation
- Current routing implementation
- Existing profile components

**Comment by mimisavage** [comment]
Could I grab this task?

**Comment by SYLVIANNORUKA** [comment]
Can I handle this task?
I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, . I would love to contribute to this project.

**Comment by 0xdevcollins** [comment]
Is this issue still available?

**Comment by codebestia** [comment]
Can i wok on this as soon as ODHack11 starts?

## How i will tackle this
- I will follow the contribution guideline to the letter
- I will follow the above description and check all the checklist
- I will open a PR within 4 days

**Comment by Ayoazeez26** [comment]
I will create a button that redirects to the main profile page and make sure it styles is consistent with the existing UI. I will improve the my-apartments view by implementing route handling and creating components for displaying apartment listings. I will also ensure consistent layout and styling. I will also improve the interested-people view by implementing route handling and creating components to display interested users/offers. I will make sure to use React Router for navigation and handle state management properly. I will handle invalid routes errors and also include loading states by adding a spinner and also make sure the components are fully responsive. Before creating a PR, I will make sure all the acceptance criteria are met.
ETA - 2 days.

**Comment by josephchimebuka** [comment]
I'd be happy to do this.

**Comment by armandocodecr** [comment]
## **Issue Submission: Profile Navigation Enhancement for Improved User Access**

**Hi** [zleypner](https://github.com/zleypner)**,**

I am excited to contribute to enhancing the profile navigation by implementing intuitive and responsive views for the **Main Profile**, **My Apartments**, and **Interested People** sections. After reviewing the issue description and the technical requirements, I propose the following structured approach to deliver a seamless and consistent user experience.

### **Proposed Solution**

**1. Profile Navigation Button**

•	**Button Implementation:**

•	Create a **Profile Navigation Button** that redirects users to the main profile page (/profile).

•	Ensure the button is prominently displayed and styled in accordance with the existing design system.

•	Use React Router’s useNavigate for efficient client-side navigation.

•	**Target URL:**

http://localhost:3000/profile

**2. My Apartments View**

•	**Route and Component Creation:**

•	Implement a new route for the path /profile/my-apartments using React Router.

•	Create a MyApartments component to display apartment listings.

•	Integrate appropriate layout and styling using the existing design system and TailwindCSS (if applicable).

•	**Key Features:**

•	Include placeholders or dynamic content for apartment listings.

•	Add loading states for data fetching and error boundaries to handle failures gracefully.

•	**Target URL:**

http://localhost:3000/profile/my-apartments

**3. Interested People View**

•	**Route and Component Creation:**

•	Implement a new route for the path /profile/interested-people using React Router.

•	Create an InterestedPeople component to display users or offers interested in the apartments.

•	Ensure the layout is user-friendly and styled consistently with the current profile design.

•	**Key Features:**

•	Display user details or offers in an organized manner.

•	Include loading indicators and error boundaries to improve user experience.

•	**Target URL:**

http://localhost:3000/profile/interested-people

### **Technical Implementation**

1.	**React Router Navigation:**

•	Use React Router for route handling to ensure smooth, client-side navigation without page refreshes.

2.	**State Management:**

•	Implement state management (e.g., using React’s useState or useContext for global state) to handle user data dynamically.

3.	**Error Handling and Loading States:**

•	Include loading indicators during data fetching to improve UX.

•	Add error boundaries to gracefully handle invalid routes or failed data fetches.

4.	**Responsive Design:**

•	Ensure all components are responsive and adapt seamlessly to mobile and desktop devices.

•	Use existing design guidelines and utilities (e.g., TailwindCSS or custom styles) for consistency.

5.	**Authentication Protection:**

•	Protect routes with authentication guards to ensure only logged-in users can access profile-related pages.

### **Acceptance Criteria**

•	✅ The **Main Profile Button** successfully redirects to /profile.

•	✅ The **My Apartments View** is accessible at /profile/my-apartments.

•	✅ The **Interested People View** is accessible at /profile/interested-people.

•	✅ All routes are protected with authentication.

•	✅ Navigation is smooth with no page refreshes.

•	✅ UI is consistent with the existing design system.

•	✅ All views are responsive on mobile and desktop devices.

### **Why This Approach?**

1.	**Consistency:**

This approach follows the current project structure and design system, ensuring seamless integration.

2.	**User Experience:**

Smooth navigation, loading states, and error handling enhance user satisfaction and reliability.

3.	**Scalability:**

The modular component design allows for easy maintenance and future enhancements.

4.	**Experience:**

With experience in React Router, state management, and responsive design, I am confident in delivering a robust solution.

### **Additional Considerations**

•	**Breadcrumb Navigation:**

To enhance usability, I suggest adding breadcrumbs to help users navigate back easily.

•	**Animations:**

Consider adding subtle animations for route transitions to improve the visual experience.

I am eager to take on this issue and deliver an improved profile navigation experience. Looking forward to your feedback!

**Comment by abdegenius** [comment]
Let me try this one!

**Comment by jimenezz22** [comment]
Hi, I'd love to contribute to this issue! I'm part of the Dojo Coding community and have experience contributing to various open-source projects in OnlyDust and I manage a full-stack developer profile. 

### My Approach:

1. **Profile Navigation Button**
    - Implement a button component styled consistently with the existing UI.
    - Configure the button to redirect to `/profile` using `React Router` for seamless navigation.
2. **My Apartments View**
    - Define a new route in the router for `/profile/my-apartments`.
    - Build a component to display apartment listings using the existing design system for layout and styling.
3. **Interested People View**
    - Add routing for `/profile/interested-people` in the router configuration.
    - Create a component to display interested users or offers with proper styling and layout.

### Technical Notes:

- Ensure state management is properly handled for data display in both views.
- Add basic loading states for data fetching to enhance user experience.
- Test the navigation to confirm routes are working as expected and protected with authentication.

ETA: few hours or a day maximum in the worst case scenario

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by SimplementeCao** [comment]
---

### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by Kachimercy1** [comment]
Let me handle this issue!

**Comment by Michaelkingsdev** [comment]
Could I be assigned to this?

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Ekene001** [comment]
Hello I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table.

Please can i be assigned to this task

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects)

**Comment by austineblaise** [comment]
**How I Can Solve the Issue**

As a frontend/JavaScript/blockchain developer, I will enhance the profile navigation by adding a visible button for the main profile page and improving views for "My Apartments" and "Interested People." I’ll handle routes with React Router, ensure responsive design, add loading states, and make the UI consistent with the existing design. Navigation will be smooth with proper error handling and authentication.

**Comment by Rayguti** [comment]
Hi, I'm a Full Stack Developer with a strong interest in continuous learning and expanding my knowledge across various scopes. I enjoy contributing to projects that challenge me and help me grow. I have previously contributed to this project and found it to be a great opportunity to develop my skills further. I’d be delighted to continue working on it and contribute to its success.

Proposed Approach.

Define requirements: Identify the routes to be implemented (profile, my apartments, interested people) and the components needed for each view.

Set up navigation: Use React Router to create the corresponding routes and ensure that views are accessible from the defined URLs.

Create components: Develop the necessary components for each view, ensuring that they display the correct data and have a consistent layout.

Manage state and authentication: Implement state management for views and ensure that routes are protected with authentication.

Include loading functionality and error handling: Add loading states for data fetching and handle potential invalid route errors.

Test and tune: Verify that all routes work correctly, that views are responsive, and that navigation does not cause page reloads. Adjust as needed to improve the user experience.

**Comment by deeseeker** [comment]
Hello, I am Qudus Adeyemi (@deeseeker), a frontend developer with over two years of experience in React, TypeScript, and JavaScript. I am currently working on a social media app for African creators (https://app.myrevva.com/).

I have reviewed the requirements carefully and will convert the designs with great attention to detail. I will consider the responsiveness, loading states, handle error and properly manage the states.

You can check out my portfolio for a sample of my work, such as Logisfi(https://logisfi-pro-app.vercel.app/), available on my GitHub.



I would love the opportunity to take on this issue.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ONEONUORA** [comment]
Is it okay if I take this? I am a full stack and blockchain developer. ETA 24 hours

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by kayceeDev** [comment]
I'd be happy to do this.

**Comment by Jonatan-Chaverri** [comment]
Can I try solving this issue?

**Comment by CoderPrime99** [comment]
Hi! I'm Carlos, a Software Developer with over 2 years of experience. I've worked with C++, Java, and JavaScript, and I'm excited to make my first contribution to OnlyDust. It would be great to contribute to the project's sucess.

I would start by checking the current project structure and how navigation is set up. Then, I’d use React Router to add routes for /profile/my-apartments and /profile/interested-people, making sure they require authentication. I’d create or update components for displaying the apartments and interested people, keeping them responsive and styled like the rest of the app. I’d add a "Profile" button to go to /profile with proper styling. To improve the experience, I’d add loading states and handle errors for broken routes. Finally, I’d test everything to make sure navigation works smoothly.

**Comment by Supa-mega** [comment]
Can I start working on this?

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


To address this task, navigation buttons and views should be implemented within the profile section to improve user access to apartments and offers. This involves adding a "Profile" button that redirects to the main profile page at http://localhost:3000/profile with styling consistent with the current UI. The My Apartments and Interested People views should be enhanced to include proper routing using React Router, as well as components for displaying apartment listings and offers. All components must maintain consistent styling, be responsive across devices, and include loading states and error handling. Routes should be protected with authentication, and navigation should be smooth, avoiding full page refreshes. Additional features like breadcrumb navigation and animations can be added to enhance user experience.

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by TheSQLguy** [comment]
I am new to open-source
To address this issue, I would improve the navigation through the profiles by adding a button for redirection to /profile with proper styling. Create views at /profile/my-apartments and /profile/interested-people by using React Router, securing routes appropriately, and making it seamless in navigating. Use responsive components for every view as per the design system; include error handling, loading states, and breadcrumbs are optional to enhance user experience.

**Comment by SimplementeCao** [comment]
Hi, I'm Leandro, Front-end developer.
I would solve the issue first by reviewing the code and adjusting to the component-based development guideline to maintain consistency and scalability of the project.
Estimated delivery time: 20 hours.

I have contributed before to other projects like:

Cairo Book
Starknet Book
Starknet Docs
Starknet Security Challenges Factory
Starkane
Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: OnlyDust Profile,
and my GitHub

**Comment by zleypner** [comment]
👋 Thank you everyone for showing interest and applying! I truly wish I could assign an issue to each one of you!! Hopefully in a next OD you will contribute in our project.

@armandocodecr , you've been assigned to this task! 🎉 Looking forward to your contribution! 💻 ✨
Let me know if you need any clarification or support as you work on this. 🤝
