### ISSUE TITLE
Replace hardcoded email with mock email in email verification page

### ISSUE THREAD

**Issue by zleypner** [safetrustcr/Frontend#118]
# Replace email with mock email in email verification page

## Description
The email verification page at `/auth/email-verification` currently displays a hardcoded email address (`josuemarin2009@hotmail.com`). This should be replaced with a default mock email for development and testing purposes.

## Changes Needed
- Remove the hardcoded email: `josuemarin2009@hotmail.com`
- Replace with mock email: `john.doe@email.com`
- Update the text in email verification page

## Location
- Path: `http://localhost:3000/auth/email-verification`

## Expected Result
The email verification page should display:
"Please check your email and type the code sent to john.doe@email.com"

## Priority
Low

## Labels
- enhancement
- development

## Type
- [ ] Bug fix
- [ ] Enhancement
- [ ] Documentation update

Please read the [CONTRIBUTORS GUIDELINE 🧪](https://github.com/safetrustcr/Frontend/issues/34)

**Comment by Joewizy** [comment]
I’d love to work on this task.

**Comment by wgorzawski** [comment]
please close this issue, the error has been fixed here https://github.com/safetrustcr/Frontend/pull/120
