### ISSUE TITLE
Update Property Listings with Diverse Pricing and Locations

### ISSUE THREAD

**Issue by zleypner** [safetrustcr/Frontend#119]
# Diversify Location and pricing information

## Description
Currently, the rental listings are concentrated in San José. We need to expand and diversify the listings to include properties across different regions and cities in Costa Rica to provide users with nationwide rental options.

## Proposed Property Listings (Minimum 10)

1. **Playa Hermosa Beachfront Villa**
  - Location: 123 Playa Hermosa Road, Guanacaste
  - Price: $2,200.00/month
  - 3 bd | 2 ba | Pet-friendly
  - Featured amenity: Ocean view

2. **Limón Downtown Apartment**
  - Location: 455 Puerto Viejo Main Street, Limón
  - Price: $750.00/month
  - 2 bd | 1 ba | Pet-friendly
  - Featured amenity: Close to beach

3. **Los Yoses Urban Living**
  - Location: 467 Los Yoses Este, San José
  - Price: $1,500.00/month
  - 2 bd | 2 ba | No pets
  - Featured amenity: Modern appliances

4. **Tamarindo Beach Condo**
  - Location: 223 Tamarindo Beach Road, Guanacaste
  - Price: $1,800.00/month
  - 2 bd | 2 ba | Pet-friendly
  - Featured amenity: Pool access

5. **Cartago Historic District**
  - Location: 789 Central Cartago, Cartago
  - Price: $900.00/month
  - 2 bd | 1 ba | No pets
  - Featured amenity: Historic building

6. **Jacó Beach Resort**
  - Location: 445 Jacó Beach Boulevard, Puntarenas
  - Price: $1,700.00/month
  - 2 bd | 2 ba | Pet-friendly
  - Featured amenity: Beach access

7. **Quepos Marina View**
  - Location: 567 Marina Drive, Puntarenas
  - Price: $1,400.00/month
  - 2 bd | 2 ba | No pets
  - Featured amenity: Marina view

8. **Alajuela City Center**
  - Location: 890 Central Alajuela, Alajuela
  - Price: $850.00/month
  - 1 bd | 1 ba | Pet-friendly
  - Featured amenity: City views

9. **Monteverde Mountain Retreat**
  - Location: 234 Cloud Forest Road, Puntarenas
  - Price: $1,100.00/month
  - 2 bd | 1 ba | Pet-friendly
  - Featured amenity: Forest view

10. **Heredia Modern Complex**
   - Location: 678 Heredia Centro, Heredia
   - Price: $1,150.00/month
   - 2 bd | 2 ba | No pets
   - Featured amenity: Security system

## Implementation Requirements
- Update location information

## Labels
- content-update

## Type
- [ ] Bug fix
- [ ] Content update

## Please read the [CONTRIBUTORS GUIDELINE 🧪](https://github.com/safetrustcr/Frontend/issues/34)

**Comment by A6dulmalik** [comment]
Mind if I try this one? I am a new contributor with experience in frontend development. I would like to take up this issue.

**Comment by davidmelendez** [comment]
Let me try this one!Hi, my name is David, and I’m a member of the ⛩️ Dojo Coding community. I’m excited about contributing to this project. This would be my first contribution here; however, I’ve been studying Web3 extensively to specialize in this field, and I have 19 years of experience in Web2 as a full-stack developer.
While my experience has been mainly in enterprise development (such as SQL Server and Oracle integrations, .NET), I am currently focusing on emerging technologies like Web3. I firmly believe this is the future, and I’m committed to fully transitioning into this area.
I’m confident that my experience and motivation can bring value to this project.
Can I start working on it? Here are my profiles:
GitHub: davidmelendez (Melendez)
OnlyDust: davidmelendez - OnlyDust

Looking forward to your feedback! 😊

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/ Can I take this issue?

**Comment by ikezuby2012** [comment]
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Reactjs, Nextjs, tailwindcss, Express.js, and recently exploring Cairo for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

i would like to work on this issue and my ETA is 8 hours

**Comment by zleypner** [comment]
👋 Thank you everyone for showing interest and applying! I truly wish I could assign an issue to each one of you!

@davidmelendez you've been assigned to this task! 🎉 Looking forward to your contribution! 💻 ✨
Let me know if you need any clarification or support as you work on this. 🤝

**Comment by davidmelendez** [comment]
Thank you very much for your trust, as soon as I start I will be asking you questions. Best regards.
