### ISSUE TITLE
Issues Template

### ISSUE THREAD

**Issue by zleypner** [safetrustcr/Frontend#123]
## Issues Template
Create an issue template to guide contributors when submitting issues. Below are some suggestions for what should be included in the template:

- **Title:** A  clear and concise title of the issue.
- **Description:** A detailed description of the issue with any relevant context.
- **Steps to Reproduce:** Provide the steps to reproduce the issue, if applicable.
- **Expected Behavior:** What should be happening?
- **Actual Behavior:** What is happening instead?
- **Environment:** The environment in which the issue was encountered (e.g., OS, version of the app, browser, etc.).
- **Screenshots/Logs:** If possible, provide any relevant screenshots or logs to help understand the issue.
- **Additional Context:** Any other information that might be helpful to resolve the issue.
- **ETA:** Please provide an estimated time of arrival for when the issue might be resolved.

---
The issue template should be added in the .github folder of the repository.

Make sure to read the [CONTRIBUTORS GUIDELINE 🧪 #7](https://github.com/safetrustcr/Landing/issues/7) before you apply.

Also, ensure that your commit follows the commit guidelines and uses atomic commits. Otherwise, the commit will be requested before the merge of the PR.  [GIT GUIDELINE 🐈](https://github.com/safetrustcr/Landing/issues/8)

**Comment by Ibinola** [comment]
Can I be assigned to this?

I have worked on documentation on an open source project [here](https://github.com/trypear/pear-landing-page/pull/93).
