### ISSUE TITLE
Change Favicon to New Design

### ISSUE THREAD

**Issue by JosueBrenes** [safetrustcr/Frontend#128]
# Change Favicon to New Design

## Description

Update the current favicon in the project with a new design provided. The new favicon file is available at the following link (access request required):

[New Favicon Design](https://drive.google.com/file/d/1Cyl_wUNRHOMAFcAASdmh5s9k1nIfVD5s/view?usp=sharing)

The favicon is located in the `app` folder.

## Steps to Complete

1. Request access to the new favicon file via the provided link.
2. Download the new favicon after access is granted.
3. Replace the current favicon file in the `app` folder with the new one (no additional changes are needed).
4. Test the changes locally to confirm the new favicon displays correctly.
5. Push the changes to the repository.

## Acceptance Criteria

- [ ] Access to the new favicon file is granted and downloaded successfully.
- [ ] The current favicon file is replaced with the new logo.
- [ ] The new favicon is successfully updated and visible in the browser.
- [ ] No errors or issues arise after the update.

**Comment by DuendexCR** [comment]
Puedo Aplicar

**Comment by anc-bhrti** [comment]
hey, if it is still not solved, can u assign me this issue ?
