### ISSUE TITLE
Update Project Colors to Default Color

### ISSUE THREAD

**Issue by JosueBrenes** [safetrustcr/Frontend#129]
# Update Project Colors to Default Color

## Description

Update the project to use a new default color across all components and styles. The steps are as follows:

1. Add a new property called `default-color` with the value `#003075` in the `tailwind.config.js` file.
2. Replace all instances of orange throughout the project with the new default color (`default-color`).
3. Ensure the changes are compatible with both light and dark modes.
4. Confirm there are no remaining orange colors in the project after the update.

## Steps to Complete

1. Open the `tailwind.config.js` file and add the following property under the `extend` section:

   ```javascript
   extend: {
     colors: {
       'default-color': '#003075',
     },
   }
   ```

2. Search for all instances of orange color (e.g., `text-orange`, `bg-orange`, hex codes, etc.) in the project.
3. Replace them with `text-default-color`, `bg-default-color`, or the appropriate usage for the new color.
4. Verify the updated styles are compatible with both light and dark modes.
5. Test the project thoroughly to ensure no orange colors remain.
6. Commit and push the changes to the repository.

## Acceptance Criteria

- [ ] The `default-color` property is successfully added to `tailwind.config.js`.
- [ ] All orange colors in the project are replaced with the new default color (`#003075`).
- [ ] The new color is compatible with both light and dark modes.
- [ ] No orange color remains anywhere in the project.

**Comment by KevinMB0220** [comment]
Hi my name is Kevin, I am part of Dojo Coding, I have experience in web development and I have already made open source contributions. I will follow all the instructions and the work will be under the expense of the issue.
