### ISSUE TITLE
Update Header Image

### ISSUE THREAD

**Issue by JosueBrenes** [safetrustcr/Frontend#130]
# Update Header Image

## Description

Replace the current header image with a new one provided at the link below. **Access request is required** to download the image.

[New Header Image](https://drive.google.com/file/d/1Cyl_wUNRHOMAFcAASdmh5s9k1nIfVD5s/view?usp=sharing)

The image should be placed in the `Frontend\public\img` folder with the following naming convention:
- `logo2.png` for dark mode
- `logolight.png` for light mode

## Steps to Complete

1. Request access to the new header image via the provided link.
2. Download the new header image after access is granted.
3. Save the image in the `Frontend\public\img` folder with two different names:
   - `logo2.png` for dark mode
   - `logolight.png` for light mode
4. Replace the current header image in the project with the new files.
5. Ensure that the new header images are properly configured to work in both light and dark modes.
6. Test the changes locally to confirm the header images display correctly in all supported themes.
7. Push the changes to the repository.

## Acceptance Criteria

- [ ] Access to the new header image is granted and the image is downloaded successfully.
- [ ] The new header images (`logo2.png` and `logolight.png`) are successfully added to the `Frontend\public\img` folder.
- [ ] The header images are compatible with both light and dark modes.
- [ ] No visual issues are present after the update.

**Comment by BigBen-7** [comment]
can i fix this?

**Comment by wheval** [comment]
Hello @JosueBrenes, I'm Wheval an experienced Frontend Developer.

I'd love to give this a go.

ETA is 1 day.

**Comment by BigBen-7** [comment]
hey, i was assigned to fix this issue, I have been requesting access to the new images but I haven't been granted that access.
