### ISSUE TITLE
Remove Prettier Configuration Files

### ISSUE THREAD

**Issue by JosueBrenes** [safetrustcr/Frontend#131]
# Remove Prettier Configuration Files

## Description

Delete the following files from the `Frontend` folder as they are no longer needed:

- `.prettierignore`
- `.prettierrc`

## Steps to Complete

1. Navigate to the `Frontend` folder.
2. Delete the files `.prettierignore` and `.prettierrc`.
3. Commit and push the changes to the repository.

## Acceptance Criteria

- [ ] The files `.prettierignore` and `.prettierrc` are successfully deleted from the `Frontend` folder.
- [ ] No related errors or issues appear after the files are removed.

**Comment by GideonBature** [comment]
Can I take this issue?

**Comment by BigBen-7** [comment]
Please let me fix this.

**Comment by wheval** [comment]
Hello @JosueBrenes, I'm Wheval an experienced Frontend Developer.

Can i fix this?.

ETA is 1 day.

**Comment by GideonBature** [comment]
Thank you ser! On it!
