### ISSUE TITLE
Remove Unused Language Flag Images

### ISSUE THREAD

**Issue by JosueBrenes** [safetrustcr/Frontend#133]
# Remove Unused Language Flag Images

## Description

Delete the following unused language flag images from the project:

- `Frontend\public\img\es.png`
- `Frontend\public\img\en.png`

These files are no longer needed and should be removed to clean up the codebase.

## Steps to Complete

1. Navigate to the `Frontend\public\img` folder.
2. Delete the files `es.png` and `en.png`.
3. Verify that no components or code references these files.
4. Commit and push the changes to the repository.

## Acceptance Criteria

- [ ] The files `es.png` and `en.png` are successfully deleted from the project.
- [ ] There are no references to these files in the codebase.
- [ ] No errors or issues occur after the files are removed.

**Comment by Yuskhosmith** [comment]
Hi,

I have created a PR for this #134

**Comment by BigBen-7** [comment]
I am up and ready for this, can it be assigned to me?

**Comment by wheval** [comment]
Hello @Yuskhosmith, You should not create a PR unless you are assigned. 🤨

**Comment by wheval** [comment]
Hello @JosueBrenes, I'm Wheval an experienced Frontend Developer.

I'd love to give this a go.

ETA is 1 day.

**Comment by zleypner** [comment]
Hello @wheval ! You have been assigned.

**Comment by Yuskhosmith** [comment]
> Hello @Yuskhosmith, You should not create a PR unless you are assigned. 🤨

Thanks, It's my first time open-sourcing. I will pick up something else 🤝🏾

**Comment by wheval** [comment]
> > Hello @Yuskhosmith, You should not create a PR unless you are assigned. 🤨
> 
> Thanks, It's my first time open-sourcing. I will pick up something else 🤝🏾
Happy hacking!
