### ISSUE TITLE
Update Text and Icon Colors

### ISSUE THREAD

**Issue by JosueBrenes** [safetrustcr/Frontend#148]
# **Issue: Update Text and Icon Colors on `/` and `/profile/my-apartments` Views**

## **Description**
Update the text and icon colors in two specific sections to use the `default-color` specified in **`tailwind.config.ts`**.

1. **Home Page (`/`)**  
   - The text **"Relevance"** in the sorting option currently has an incorrect red color.

2. **Profile Apartments Page (`/profile/my-apartments`)**  
   - The "Promoted" icons use an orange color that does not align with the defined design scheme.

---

#### **Requirements**
1. **Text on `/`**  
   - Replace the current color with the `text-default-color` class.
   
   Example:
   ```tsx
   <span className="text-default-color cursor-pointer hover:underline ml-1">
     {t(sortOption.name)}
   </span>
   ```

2. **Promoted Icons on `/profile/my-apartments`**  
   - Update the icons to use the `text-default-color` class.
   
   Example:
   ```tsx
   <Icon className="text-default-color" />
   ```
---

#### **Additional Steps**
- Verify that `text-default-color` is applied correctly in the affected components.
- Review the `/` and `/profile/my-apartments` views to confirm the changes.

---

**Comment by Jagadeeshftw** [comment]
Hi @JosueBrenes, I'd like to work on this issue?
