### ISSUE TITLE
Implement User Profile Update Operations

### ISSUE THREAD

**Issue by rvalenciano** [safetrustcr/Frontend#151]
### 📝 Title

Implement User Profile Update Operations

### 🔍 Description

Following the structure of a query implemented on [this](https://github.com/safetrustcr/Frontend/pull/71) 

But implementing a mutation.

### 🔄 Steps to Reproduce

1. Run the backend 
2. Run the frontend
3. Go to the user profile page.
4. Fill the data in the user profile page:

![image5](https://github.com/user-attachments/assets/c176663d-e229-4cde-aff8-569d3ef778f2)

When clicking the submit button, the following mutation should be invoked.

```
# Update user profile
mutation UpdateUserProfile($userId: String!, $input: users_set_input!) {
  update_users_by_pk(
    pk_columns: { id: $userId },
    _set: {
      first_name: $input.first_name,
      last_name: $input.last_name,
      summary: $input.summary,
      phone_number: $input.phone_number,
      country_code: $input.country_code,
      location: $input.location
    }
  ) {
    id
    first_name
    last_name
    summary
    phone_number
    country_code
    location
    email
    profile_image_url
    user_wallets {
      id 
      wallet_address
      chain_type
      is_primary
    }
  }
}

# Update profile image
mutation UpdateProfileImage($userId: String!, $imageUrl: String!, $imageKey: String!) {
  update_users_by_pk(
    pk_columns: { id: $userId },
    _set: {
      profile_image_url: $imageUrl,
      profile_image_r2_key: $imageKey
    }
  ) {
    id
    profile_image_url
  }
}
```

For the profile_image_url, we can use any random URL of it since we need to implement the integration with the S3 bucket image upload from Cloudflare R2 in a separate issue.

### 👌🏼 Expected Behavior

- [ ]  Profile updates working
- [ ]  Image upload integrated with R2
- [ ]  Phone validation working
- [ ]  Country code validation working
- [ ]  Proper error handling
- [ ]  Optimistic updates

### ✅ Actual Behavior

User data profile should be persisted in the database.

**Comment by Jagadeeshftw** [comment]
I’d like to resolve this.

**Comment by Birdmannn** [comment]
Please id like to work on this task. I'm an experienced frontend developer.

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue.

## My approach:
I will fork the project and clone locally, and then set up the dev environment. 
I will have a look at the reference query to see what I require and what I'm changing in order to implement this mutation successfully. 
I will run the backend and frontend as stated in the description, and invoke the appropriate mutation
I will make sure of error and type safety, and that the data is fetched successfully from the backend. 
After that, I will feed it to the user through the UI. 
Before I make a PR, I'll double check this description to make sure it passes all the requirements. 

Expect my first PR within 36 - 48 hours of assignment

**Comment by olisaagbafor** [comment]
Can I jump on this task?

**Comment by ryzen-xp** [comment]
May I handle this issue?

**Comment by Michaelkingsdev** [comment]
Can i be assigned to this issue?


### Here is My Approach
- I will create a new mutation in the GraphQL schema to update the user profile, taking into account the necessary inputs such as user ID and updated profile information.
- I will Implement phone and country code validation functions to ensure that the input data is correct and return errors if not.
- I will develop an error handling function to catch and handle any errors that occur during the update process, providing user-friendly error messages.
- I will Integrate the update profile image mutation with the S3 bucket image upload functionality from Cloudflare R2.
- And finally, I will Implement optimistic updates to update the user profile information in the client-side cache before the mutation is resolved, providing a better user experience.

**Comment by MrRoudyk** [comment]
I'd love to give this a go.

**Comment by emarc99** [comment]
Could I take a shot at this?

**Comment by akintewe** [comment]
Hello i am akintewe a Full Stack Developer with experience in Next.js/React, TypeScript, and Rust.  I am happy to work on this task

To build User Profile Update Operations, I will write GraphQL mutations, validate inputs, and integrate them into a frontend form. Optimistic updates will improve the user experience, including error handling for failures. 


I would love if i am given the opportunity 
ETA is 24 hours.

**Comment by aurlic** [comment]
Hey I would be really interested to work on this. I think this issue would be a great occasion to improve my skills. Thanks in advance !

**Comment by Thibrac** [comment]
May I try my hand at this?

**Comment by Psalmuel01** [comment]
# I am super experienced in both web2/web3 frontend integrations.

**About me**:
I am a software engineer with strong technical skills and expertise in developing fully functional applications. I also have experience in writing a little backend, so I know the modalities around it. I have developed many such frontends with excellent integrations as you'd find all around my repos.

Lately I've been doing more of integrations, and I find that its my forte. My GitHub has a lot of proof of work, as well.

Leveraging on my skills and experience, l am confident in my ability to tackle new challenges and also solve complex technical issues.

Tackling this issue
• Given my experience in integrating frontend with backends, I will ensure the frontend is exactly configured to fit the databases, until it functions seamlessly.

ETA: 12 hours

**Comment by omsant02** [comment]
I would like to take this issue,
This would be my first contribution SafeTrust and i want to start my contribution journey with SafeTrust

My approach would be:

-Implement the basic profile update mutation first using the provided GraphQL schema, with proper form validation and error handling
-Then tackle the profile image upload feature by integrating with S3/Cloudflare R2, implementing it as a separate PR to keep changes focused and reviewable.

ETA : 1 day

**Comment by Supa-mega** [comment]
Can I attempt this issue?

**Comment by mimisavage** [comment]
I'd love to work on this!

**Comment by blessingbytes** [comment]
I would love to tackle this issue.

**Comment by savagechucks** [comment]
Hey, My name's Isaac, I'm a frontend dev. I'd like to take on this issue.
ETA: 2days

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, Cairo and Rust.

I will like to take care of this.

**Comment by phertyameen** [comment]
I am new contributor and I can handle this issue following the stated guidelines, kindly assign it to me.

**Comment by Rayguti** [comment]
Hi, I'm a Full Stack Developer with a strong interest in continuous learning and expanding my knowledge across various scopes. I enjoy contributing to projects that challenge me and help me grow. I have previously contributed to this project and found it to be a great opportunity to develop my skills further. I’d be delighted to continue working on it and contribute to its success.
Approach:
Define Requirements: Analyze the current query implementation to understand the structure, logic, and dependencies. Identify the fields required for user profile update mutations and ensure they meet the required validations (such as phone and country code).

Create Mutations: Develop the UpdateUserProfile and UpdateProfileImage mutations using the schema provided. Ensure the fields are consistent with the expected data in the database and frontend.

Prepare Validations: Implement validations on the frontend to ensure that entered data, such as phone number and country code, meet accepted formats before submitting the mutation.

Implement Error Handling: Add robust error handling for mutations on the frontend, displaying clear messages to the user in case of failures during the update.

Configure Optimistic Updates: Configure optimistic updates to ensure the UI reflects immediate changes while the operation is being completed on the backend.

Test and Tune: Perform full testing of the profile update flow, including data changes and image uploads with random URLs. Ensure validations work correctly and data is persisted to the database.

Prepare for R2 Integration: Ensure the UpdateProfileImage mutation is ready to integrate with image uploads to the Cloudflare R2 S3 bucket in future tasks.

Document the Process: Provide clear instructions in the repository on how to test and validate the implemented functionality.

**Comment by fabrobles92** [comment]
Hello I am Fab member of Dojo Coding. I would like to start working on this issue right away :)

I can send a PR within 24h at most

**Comment by Jemiiah** [comment]
Hello @rvalenciano. Please, Let me handle this issue!

**Comment by ikemHood** [comment]
Hello @rvalenciano, Can I be assigned to this?
I am conversant with working with graphql

**Comment by 0xNgoo** [comment]
Mind if I try this one?
i am a frontend developer with 2+ yrs expirence and i have worked with graphql before
EDT: 24hrs

**Comment by yusuftomilola** [comment]
Is this issue still available? Can i apply for this?

**Comment by danielrobotz** [comment]
Can I contribute to this one?

**Comment by KuchiMercy** [comment]
I’m interested in this one.

**Comment by jaykayudo** [comment]
Can I take this from here?

**Comment by Ibinola** [comment]
I'd like to handle this task.

**Comment by Pvsaint** [comment]
I'd love to work on this if it's still available

**Comment by lalitkumawat1m** [comment]
Can I try solving this issue?

**Comment by Nityam573** [comment]
Could I take over this issue?

**Comment by ekumamatthew** [comment]
I’d love to work on this task.

**Comment by Birdmannn** [comment]
Hey Dev. I'm Torti. I'm a good frontend engineer and I would love to work on this task.

I have experience in solving bugs and completing tasks. Feels good.
ETA < 2 days

**Comment by Amarjeet325** [comment]
May I take this issue on?

**Comment by Kingsuite** [comment]
Can I try solving this issue? 
Contributing to issue; "143 chore: remove test/components folder (#140)" was exciting. ETA about 48hrs

**Comment by simlf** [comment]
Can I contribute to this one?

**Comment by otuoche** [comment]
I’d like to help with this.

**Comment by od-hunter** [comment]
Hello, can I be assigned this please? I’m ready to work.

**Comment by 1nonlypiece** [comment]
I'd like to handle this task.

**Comment by Superfly101** [comment]
I would love to give this a go. I am familiar with the technologies used here (ReactJs, GraphQL)

**Comment by diegoTech14** [comment]
@fabrobles92 just assigned, don't hesitate if you have any question! 🚀
