### ISSUE TITLE
 Implement Paid State Bid Request Page

### ISSUE THREAD

**Issue by rvalenciano** [safetrustcr/Frontend#69]
Develop the "Paid State Bid Request" page based on the provided mockup design: [Mockup SafeTrust](https://www.figma.com/design/CVg9hoim0f1FIlozIar7ZZ/SafeTrust?node-id=49-2&node-type=canvas&t=OcHooDr4NKQpocMe-0).

<img width="796" alt="Screenshot 2024-11-20 at 00 38 54" src="https://github.com/user-attachments/assets/edf85cb4-a79d-4f85-b978-f8dfc03f91f1">

## Problem

We need to create a detailed paid state view for bid requests that shows:
- Payment invoice details
- Apartment information
- Payment process status
- Notes section
- Terms and conditions

## Solution

(This is a proposed solution). Please use hardcoded data for now, the backend would be connected later.

### Component Structure
```typescript
src/
└── features/
    └── bids/
        ├── components/
        │   ├── InvoiceHeader/
        │   ├── InvoiceDetails/
        │   ├── PaymentTable/
        │   ├── ProcessTimeline/
        │   └── NotesSection/
        └── pages/
            └── PaidStateBidRequest.tsx
```

### Main Component Implementation
```typescript
// src/features/bids/pages/PaidStateBidRequest.tsx
import { useQuery } from '@apollo/client';
// import { GET_BID_REQUEST_DETAILS } from '../graphql/queries';
import { 
  InvoiceHeader,
  InvoiceDetails,
  PaymentTable,
  ProcessTimeline,
  NotesSection
} from '../components';

interface BidRequestDetailsProps {
  bidId: string;
}

export const PaidStateBidRequest: React.FC<BidRequestDetailsProps> = ({ bidId }) => {
 // const { data, loading } = useQuery(GET_BID_REQUEST_DETAILS, {
    variables: { id: bidId }
  });

  if (loading) return <LoadingSpinner />;

  const { invoice, apartment, payment } = data.bidRequest;

  return (
    <div className="max-w-7xl mx-auto p-6">
      {/* Top Navigation Bar */}
      <nav className="flex justify-between items-center mb-8">
        <div className="flex items-center gap-4">
          <img src="/logo.svg" alt="SafeTrust" className="h-8" />
          <select className="border rounded-md px-3 py-2">
            <option>Rent</option>
          </select>
          <div className="relative">
            <input 
              type="text"
              placeholder="City, province or neighborhood"
              className="pl-10 pr-4 py-2 rounded-md bg-gray-100 w-96"
            />
            <SearchIcon className="absolute left-3 top-1/2 transform -translate-y-1/2" />
          </div>
        </div>
        <div className="flex items-center gap-4">
          <NotificationBell />
          <UserAvatar name="Randall Valenciano" />
        </div>
      </nav>

      {/* Main Content */}
      <div className="grid grid-cols-3 gap-8">
        {/* Left Column - Invoice Details */}
        <div className="col-span-2">
          <InvoiceHeader 
            invoiceNumber="INV4257-09-012"
            status="Paid"
            date="25 Jan 2025"
          />

          <div className="bg-white rounded-lg shadow p-6 mt-4">
            <h2 className="text-2xl font-bold mb-6">
              Payment batch January 2025
            </h2>

            <InvoiceDetails
              billedTo={{
                email: "John_s@gmail.com",
                name: "John Smith"
              }}
              details={{
                invoiceNumber: "INV4257-09-012",
                subject: "Rent service",
                currency: "IDR - Dollar",
                issued: "20 January 2025",
                dueDate: "30 January 2025"
              }}
            />

            <PaymentTable
              products={[
                {
                  name: "La sabana apartment",
                  pricePerMonth: 4000,
                  deposit: 4000,
                  image: "/apartment-thumbnail.jpg"
                }
              ]}
              subtotal={4000}
              total={8000}
              discount={0}
            />

            <div className="mt-8">
              <h3 className="text-lg font-semibold mb-4">Terms & Condition</h3>
              <p className="text-gray-600">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry...
              </p>
            </div>
          </div>
        </div>

        {/* Right Column - Notes & Process */}
        <div className="space-y-6">
          <NotesSection 
            notes="Lorem Ipsum is simply dummy text of the printing and typesetting industry..."
          />

          <ProcessTimeline
            steps={[
              {
                icon: "home",
                text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
              },
              {
                icon: "camera",
                text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
              },
              {
                icon: "document",
                text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
              },
              {
                icon: "user",
                text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
              }
            ]}
          />
        </div>
      </div>
    </div>
  );
};
```

#### ProcessTimeline Component
```typescript
// src/features/bids/components/ProcessTimeline/index.tsx
interface TimelineStep {
  icon: string;
  text: string;
}

interface Props {
  steps: TimelineStep[];
}

export const ProcessTimeline: React.FC<Props> = ({ steps }) => {
  return (
    <div className="bg-white rounded-lg shadow p-6">
      <h2 className="text-xl font-semibold mb-6">Process</h2>
      <div className="space-y-6">
        {steps.map((step, index) => (
          <div key={index} className="flex items-start gap-4">
            <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center">
              <Icon name={step.icon} className="text-green-600" />
            </div>
            <div className="flex-1">
              <p className="text-gray-600">{step.text}</p>
            </div>
            {index < steps.length - 1 && (
              <div className="absolute left-4 h-full border-l-2 border-gray-200" />
            )}
          </div>
        ))}
      </div>
    </div>
  );
};
```

### Colors
- Background: Light gray (#F8F9FA)
- Primary Text: Dark gray (#2D3748)
- Secondary Text: Gray (#718096)
- Success Green: (#10B981)
- Card Background: White

### Typography
- Invoice Number: 24px, Bold
- Section Titles: 20px, Semibold
- Body Text: 16px, Regular
- Table Headers: 14px, Medium

### Layout
- Two-column layout
- Left column (2/3 width): Invoice details
- Right column (1/3 width): Notes and Process
- Responsive design for tablet/mobile

## Success Criteria
- [ ] Matches design mockup exactly
- [ ] Displays all invoice details correctly
- [ ] Shows payment status clearly
- [ ] Process timeline implemented
- [ ] Notes section working
- [ ] Responsive layout
- [ ] Proper error handling
- [ ] Loading states implemented

## Additional Context
- Navigation should be functional
- Search bar should be implemented
- User profile menu needs to work
- All amounts should be properly formatted
- Dates should be in consistent format
- Invoice number should be easily copyable

## Related Issues
- #XX User Authentication
- #XX Bid Request Flow
- #XX Payment Integration

Would you like me to:
1. Add responsive breakpoints?
2. Show loading state components?
3. Add animation effects?
4. Include print functionality?

**Comment by ShantelPeters** [comment]
May I take this issue on?

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by Unickhub** [comment]
I'd like to handle this task.

**Comment by MayowaObisesan** [comment]
I am a web3 frontend developer with full-stack development experience.
I have worked on various frontend projects building exciting and captivating UI for good User Experience. I believe in pixel-perfect design and UI implementations.
I have a knack for building amazing web and mobile UI.

Once I have understood the problem, I will fork the repo and simulate the issue that was described. Depending on the complexity of the issue. If it is a frontend issue with an easy tag, I can raise a PR in minutes, but for more complex UI, it takes longer to raise a PR.

**Comment by qgatssdev** [comment]
Hello, I'm Uche a fullstack engineer with over 4 years of experience. Implementation of the design should have an ETA of <=4 days. I can get a working PR before then.

**Comment by Ekene001** [comment]
I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

To tackle this task,  I will create a responsive and user-friendly interface that aligns with the design requirements. This page will display payment invoice details, apartment information, payment process status, a notes section, and terms and conditions. Using hardcoded data for now, I will ensure the frontend is ready for eventual backend integration.

I’ll create a two-column layout, the left for invoice details and the right for notes and process timelines. The design will include a clean, professional look with light gray backgrounds, white cards, and appropriate typography for clear readability. I will build reusable components such as InvoiceHeader, InvoiceDetails, and ProcessTimeline to maintain modularity and scalability.

To ensure functionality, i will ensure that the components simulate dynamic data using predefined values. I will also test the page thoroughly to verify its compliance with the mockup and readiness for backend connection.

**Comment by MullerTheScientist** [comment]
hello can i please work on this issue

**Comment by melnikga** [comment]
Can I take this?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by KevinMB0220** [comment]
Hi my name is Kevin, I'm part of Dojo Coding, I'm a fullstack developer, I would like to raise this issue and follow the best practices to resolve it.

**Comment by CristopherAguilar10** [comment]
Hi, I have experience in frontend application design. I am currently a leader in the Citizen of Arcanis project and previously I have worked in projects like Bytebeast, and I am also part of the Dojo.
I would like to contribute to this issue and help meet the defined acceptance criteria.

**Comment by rvalenciano** [comment]
Hey @KevinMB0220 , feel free to work on this one

**Comment by JosueBrenes** [comment]
Hi @KevinMB0220. How are you going with the problem?

**Comment by KevinMB0220** [comment]
Hi, good tomorrow i will open the PR
