### ISSUE TITLE
# Implement Dark Mode Feature

### ISSUE THREAD

**Issue by zleypner** [safetrustcr/Frontend#74]
The application needs a dark mode feature to allow users to switch between a light and dark theme.

## Problem
Currently, the application only supports a light theme, which may not be preferred by all users. Providing a dark mode option will improve accessibility and user experience.

## Solution
Implement a dark mode feature that allows users to toggle between light and dark themes.

---

## Technical Requirements

1. **Create a new theme context to manage the current theme state**
2. **Add functionality to toggle the theme (light/dark) using a button or setting**
3. **Persist the selected theme in the browser's localStorage**
4. **Update the application's styles to support both light and dark themes**
5. **Ensure seamless transition between the two themes**

---

## Theme Implementation

- **Light Theme**: White background with dark text.
- **Dark Theme**: Black/dark background with light text.

### Components to Update
1. Header
2. Footer
3. Card
4. Button
5. Input fields
6. Any other major UI elements

---

## Folder Structure
```tsx
src/
  contexts/
    theme.tsx
  components/
    theme/
      ThemeToggle.tsx
  styles/
    globals.css
    light.css
    dark.css
```

---

## Acceptance Criteria

1. Users can toggle between light and dark themes.
2. The selected theme is persisted in the browser's localStorage.
3. All major UI elements have consistent styling for both light and dark themes.
4. Switching between themes is smooth and seamless.
5. The dark theme uses appropriate colors for a pleasant user experience.

---

## Testing

1. **Verify** that the theme toggle functionality works as expected.
2. **Ensure** that the selected theme is properly persisted in localStorage.
3. **Test** the application in both light and dark modes to validate the styling.
4. **Ensure** that the transition between themes is smooth.
5. **Perform accessibility testing** to confirm appropriate color contrast.

**Comment by pheobeayo** [comment]
Hello @JosueBrenes  @zleypner 
Can I tackle this issue?

I am a skilled web3 frontend developer. I have skills in Next js and React js, both in Typescript and Javascript. I have successfully contributed to projects on the Onlydust platform.
I plan to tackle this by implementing the dark theme and the required components in the highlighted folder. 

Ensure the theme is persisted in the browser's local storage. Provide a seamless switch between the two themes. Test the codes and ensure this doesn't break the codebase.

**Comment by martinvibes** [comment]
Could I grab this task?
i would love to work on this issue kindly assign :)

**Comment by Immanuelolivia1** [comment]
I'd be happy to do this.

**Comment by caxtonacollins** [comment]
I'd like to take this issue.

**Comment by Benjtalkshow** [comment]
Can I attempt this issue?
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by Awointa** [comment]
I would really appreciate implementing this feature as my first issue

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by Bran18** [comment]
Hello there, I’m Brandon, part of the Dojo Coding community, and I would love to contribute to this project! 🚀 (PS: This might be my first contribution here)

I've done a couple of D/W modes for our masterbots.ai and the other apps we currently have as DeFis and DAOs, and I believe I can help u out a little xD. I would love to bring value to this project you’re building 🙏

Here’s my GitHub profile: GitHub: https://github.com/Bran18 and my OnlyDust profile: https://app.onlydust.com/u/Bran18. 

BTW tks for taking the time and for this opportunity!

**Comment by ShantelPeters** [comment]
Can I tackle this one?

**Comment by mimisavage** [comment]
Can I start working on this?

**Comment by Ayoazeez26** [comment]
Could I try solving this?
I would make use of tailwind's `dark:` utility class to implement the dark mode to meet all requirements and ensure they work as they should before making a PR

ETA - 2-days

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


 I would create a global context (ThemeContext) to manage the theme state, enabling users to toggle between light and dark modes with a button. I would utilize localStorage to persist the user's preference and automatically load it on application startup. The styling would be handled using dynamic CSS classes (light and dark) applied at the root level to ensure a seamless transition across all key components, such as the Header, Footer, buttons, and input fields. Additionally, I would implement smooth CSS transitions to enhance the user experience when switching themes.

**Comment by wheval** [comment]
Hello, I'm Wheval an experienced frontend developer.

I have experience Implementing dark mode on websites.
Here's how I plan to tackle this, 
I would create a theme context that persists using localStorage of the browser.
I would follow the code structure provided above when implementing this. 
I would also update the styles of the components listed above to adapt to the themeContext state.
I would create a toggle button for seamless transition between themes. I would also make sure the toggle button adapts to the current UI.

I would ensure to test it and make a draft PR to keep you posted with my progress.
Please assign, thank you.

ETA is 3days max.

**Comment by AnoukRImola** [comment]
Hi Guys! I'm a Frontend Developer and part of the Dojo. I have experience with this type of implementation.

There are several ways to tackle this, from using Tailwind's built-in "Dark Mode" system to creating a custom "ThemeContext" to manage the global theme state. I would coordinate with the maintainers to determine the most viable option depending on the project's future requirements :)

**Comment by Kingsuite** [comment]
I’d like to resolve this.

It's my first time contributing here. 
I will be glad to jump on it

**Comment by MullerTheScientist** [comment]
hello would love to address this issue

**Comment by zleypner** [comment]
Hey @AnoukRImola you have been assigned

**Comment by stephanniegb** [comment]
Can I  work on this? I have extensive experience building frontend applications, so I know how to manage state while keeping a website performant. I’d love to contribute to this project!

Here’s what I’d do:

- Implement dark mode using theme context.
- Add a toggle button to switch themes and store the selected theme in local storage.
- Make sure the transition between themes looks smooth and polished.
- Ensure the contrast is accessible for all users.
If you’d like, I can also set the initial theme to match the user’s preferred theme on their device.
Let me know what you think!
