### ISSUE TITLE
Create the email verification screen

### ISSUE THREAD

**Issue by zleypner** [safetrustcr/Frontend#75]
# Create the email verification screen that users see after registration, displaying a code input interface with resend functionality.

## Problem
We need to:
- Create a verification code input screen
- Display user's email address
- Implement resend code functionality
- Match the provided design mockup
- Ensure mobile responsiveness

## Solution

(This is a suggested solution, not the only one)

![image](https://github.com/user-attachments/assets/84b78397-81d3-47ad-a8ad-f592d0824fe2)

Develop the "Email Verification" page based on the provided mockup design: [Mockup SafeTrust](https://www.figma.com/design/CVg9hoim0f1FIlozIar7ZZ/SafeTrust?node-id=49-2&node-type=canvas&t=OcHooDr4NKQpocMe-0).

### Component Structure
```typescript
src/
└── features/
    └── auth/
        ├── components/
        │   ├── VerificationCodeInput/
        │   │   ├── index.tsx
        │   │   └── styles.css
        │   └── CityBackground/
        │       ├── index.tsx
        │       └── styles.css
        └── pages/
            └── EmailVerification.tsx
```

#### EmailVerification Page
```typescript
// src/features/auth/pages/EmailVerification.tsx
import { useState } from 'react';
import { useLocation } from 'react-router-dom';
import { VerificationCodeInput } from '../components/VerificationCodeInput';
import { CityBackground } from '../components/CityBackground';

export const EmailVerification = () => {
  const [isResending, setIsResending] = useState(false);
  const location = useLocation();
  const email = location.state?.email;

  const handleResendCode = async () => {
    setIsResending(true);
    try {
      // Resend logic here
    } finally {
      setIsResending(false);
    }
  };

  return (
    <div className="min-h-screen flex flex-col items-center justify-center p-4">
      <div className="max-w-md w-full space-y-8 text-center">
        <h1 className="text-3xl font-bold">Check your E-mail</h1>
        <p className="text-gray-600">
          Please, check your email and type the code sent to the{' '}
          <span className="font-medium">{email}</span> address
        </p>
        
        <VerificationCodeInput length={6} onComplete={(code) => {
          // Handle verification
        }} />

        <button
          onClick={handleResendCode}
          disabled={isResending}
          className="w-full py-3 px-4 bg-orange-500 text-white rounded-md hover:bg-orange-600 disabled:opacity-50"
        >
          {isResending ? 'Sending...' : 'Resend code'}
        </button>
      </div>
      <CityBackground className="fixed inset-x-0 bottom-0 z-[-1]" />
    </div>
  );
};
```

#### Verification Code Input Component
```typescript
// src/features/auth/components/VerificationCodeInput/index.tsx
import { useState, useRef } from 'react';

interface Props {
  length: number;
  onComplete: (code: string) => void;
}

export const VerificationCodeInput: React.FC<Props> = ({ length, onComplete }) => {
  const [code, setCode] = useState<string[]>(Array(length).fill(''));
  const inputs = useRef<(HTMLInputElement | null)[]>([]);

  const handleChange = (index: number, value: string) => {
    if (!/^\d*$/.test(value)) return;
    
    const newCode = [...code];
    newCode[index] = value;
    setCode(newCode);

    // Move to next input
    if (value && index < length - 1) {
      inputs.current[index + 1]?.focus();
    }

    // Check if code is complete
    if (newCode.every(digit => digit) && newCode.join('').length === length) {
      onComplete(newCode.join(''));
    }
  };

  return (
    <div className="flex gap-2 justify-center my-8">
      {code.map((digit, index) => (
        <input
          key={index}
          ref={el => inputs.current[index] = el}
          type="text"
          maxLength={1}
          value={digit}
          onChange={e => handleChange(index, e.target.value)}
          className="w-12 h-12 text-center text-xl border rounded-md focus:border-orange-500 focus:ring-1 focus:ring-orange-500"
        />
      ))}
    </div>
  );
};
```

### Colors
- Primary Button: `bg-orange-500`
- Button Hover: `bg-orange-600`
- Background: White
- Text: Black/Gray scale

### Typography
- Heading: 30px, Bold
- Body Text: 16px, Regular
- Email Address: 16px, Medium

### Layout
- Centered content
- Maximum width: 448px
- 6-digit verification code input
- City illustration as background
- Responsive on all devices

## Success Criteria
- [ ] Matches design mockup exactly
- [ ] Verification code input works correctly
- [ ] Resend functionality implemented
- [ ] Shows correct user email
- [ ] Proper error handling
- [ ] Loading states implemented
- [ ] Mobile responsive
- [ ] Accessible

## Additional Context
- Code inputs should only accept numbers
- Auto-focus next input when digit entered
- Show loading state during resend
- Keep city illustration responsive
- Handle paste functionality for code

## Related Issues
- #XX User Registration Flow
- #XX Firebase Auth Integration

Would you like me to:
1. Add keyboard navigation logic?
2. Show error state styles?
3. Add animation effects?
4. Include form validation logic?

**Comment by Kingsuite** [comment]
Can I try solving this issue?

**Comment by Akshola00** [comment]
Can I tackle this one?
would love to work on this issue

**Comment by KodeSage** [comment]
Would love to tackle this!

**Comment by khayss** [comment]
I’d like to work on this.

## Background
I have experience in building form-based screens in Next.js, with focus on responsiveness and user interaction.

## Plan
- Create a code input form and display the user’s email.
- Implement "Resend Code" button.
- Ensure mobile responsiveness.
- Test the layout and functionality.

**Comment by nov0ax** [comment]
Hey team, I'd like to work on this issue, I'm part of the Dojo coding CR comunity and have been working on my path as frontend dev. I currently work with JS and would like to put in practice all the knowledge in this issue.

I'm very attentive to detail on design requirements and QA process to make sure everything will be covered as requested in different environments and tools.

**Comment by Benjtalkshow** [comment]
Can I attempt this issue?
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by ShantelPeters** [comment]
Can I work on this, please?

**Comment by abdegenius** [comment]
I’m interested in this one.Would love to tackle this! I can comfortably handle this issues

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by Michaelkingsdev** [comment]
I'd be happy to do this.

**Comment by KevinLatino** [comment]
Hello @JosueBrenes My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding ⛩️, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar. 

I will create a verification code input screen that displays the user's email address. The screen will include a "resend code" functionality, and will be styled according to the provided design mockup. It will also be fully responsive for mobile devices.

Here is an example of a Frontend Project that I have made: 
https://buildmyevent.xyz/

**Comment by KevinLatino** [comment]
Hello @zleypner My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding ⛩️, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base. I've also contributed to projects in ecosystems like Starknet and Stellar.

I will create a verification code input screen that displays the user's email address. The screen will include a "resend code" functionality, and will be styled according to the provided design mockup. It will also be fully responsive for mobile devices.

Here is an example of a Frontend Project that I have made:
https://buildmyevent.xyz/

**Comment by Villarley** [comment]
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I would follow all the guidelines and instructions to get exactly what you want.
Pls feel free to reach out!

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by gidson5** [comment]
First time contributor, I'd like to hop on this please

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus a Developer with experience in both front-end and back-end, and I would love to tackle this issue head on. With my proficiency in TypeScript and experience working on the front-end aspects of my last few hackathons I'm confident that I can contribute to this project efficiently. 

My workflow:

- Create a verification code input screen
- Display the user's email address on the screen
- Include a "resend code" functionality
- Style the screen according to the provided design mockup
- Ensure the screen is fully responsive for mobile devices

**Comment by emmz3230** [comment]
Can I jump on this task?

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

will gladly like to work on this issue by checking the code to see if it is the same with the code and not just a random code using the design shown above 
Thanks

**Comment by CristopherAguilar10** [comment]
Hi, I have experience in frontend application design. I am currently a leader in the Citizen of Arcanis project and previously I have worked in projects like Bytebeast, and I am also part of the Dojo.
I would like to contribute to this issue and help meet the defined acceptance criteria.

**Comment by Josue19-08** [comment]
Hi, I'm Josué, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way. Additionally, I’m working on the project Citizen Of Arcanis, where I’ve had to use Unity, so I’m also skilled with this tool.

I’ll create the EmailVerification page based on the description. It will use useLocation to display the user’s email and include a VerificationCodeInput component for a 6-digit code with auto-focus and validation. A resend button will handle re-sending with a loading state. The design will follow the mockup with centered content, responsive layout, and a decorative CityBackground. It will ensure accessibility, accept only numbers, and support keyboard navigation.

**Comment by zleypner** [comment]
Hey @Villarley,  you have been assigned

**Comment by Villarley** [comment]
> Hey @Villarley, you have been assigned

Thank you so much sir!!! working on it
