### ISSUE TITLE
Create "Reset password" view

### ISSUE THREAD

**Issue by diegoTech14** [safetrustcr/Frontend#87]
# Create "Reset password" View
This view is required to give the user the ability to receive a temporary password via email

## Problem
There is currently no interface for reset password 

## Solution
Develop the "Reset password" page following the design in the provided mockup: ![image](https://github.com/user-attachments/assets/86667c1e-b0a5-453e-93e9-29cf5857dc56)

### Technical Specifications
- The view must be responsive

### UI/UX Considerations
- [ ] Ensure the design is visually consistent with the platform's style
- [ ] Highlight the "Send password" button for better visibility
- [ ] Use fresh password and arrow icons

## Acceptance Criteria
1. The UI/UX it's very faithful to the figma
2. Colors are the same to the figma

**Comment by akintewe** [comment]
Hello good day , i am akintewe and i would love to work on this issue

i have experience in frontend development and integration, and i would love to work on this task as my first issue. So excited :) 

Ill make sure the screen is very responsive 

my ETA is >24 hours

**Comment by Michaelkingsdev** [comment]
Hello @diegoTech14
I am a frontend developer with 3 years of experience. I can easily handle this task. I will test thoroughly to see it is fully responsive and adaptive across different screen sizes. My ETA is 48hrs.

**Comment by Emmanex01** [comment]
I'd love to give this a go.

**Comment by ooochoche** [comment]
I have gone through the description, the problem and the intended solution and I can resolve the task and meet the accepted criteria

**Comment by mimisavage** [comment]
I'd be happy to do this.

**Comment by Yunusabdul38** [comment]
I’d like to work on this.
and make sure it meets the requirements

**Comment by JosueBrenes** [comment]
Hi @akintewe have assigned the issue to you, many thanks to everyone else for applying.

**Comment by akintewe** [comment]
thank you so much
