### ISSUE TITLE
Create the "New password" view

### ISSUE THREAD

**Issue by diegoTech14** [safetrustcr/Frontend#88]
# Create "New password" View
This view is required to give the user the ability to change the password using the temporal password

## Problem
There is currently no interface for change password

## Solution
Develop the "New password" page following the design in the provided mockup: ![image](https://github.com/user-attachments/assets/a6303a3b-dded-416d-8071-11241710635c)

### Technical Specifications
- The view must be responsive

### UI/UX Considerations
- [ ] Ensure the design is visually consistent with the platform's style
- [ ] Highlight the "Save" button for better visibility
- [ ] Use fresh password icon

## Acceptance Criteria
1. The UI/UX it's very faithful to the figma
2. Colors are the same to the figma

**Comment by akintewe** [comment]
Hello good day , i am akintewe and i would love to work on this issue

i have experience in frontend development and integration, and i would love to work on this task as my first issue. So excited :) 

my ETA is >24 hours

**Comment by Michaelkingsdev** [comment]
Hello @diegoTech14 
I am a frontend developer with 3 years of experience. I can easily handle this task. I will test thoroughly to see it is fully responsive and adaptive across different screen sizes. My ETA is 48hrs.

**Comment by 0xdevcollins** [comment]
I’d like to help with this.

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Emmanex01** [comment]
Hi, Can I contribute to this one?
I'm frontend developer with few years of experience.

**Comment by mimisavage** [comment]
I’d like to work on this.

**Comment by Yunusabdul38** [comment]
I’d like to work on this.
and make sure it meets the requirements

**Comment by JosueBrenes** [comment]
Hi @mimisavage have assigned the issue to you, many thanks to everyone else for applying.

**Comment by sotoJ24** [comment]
Hi @mimisavage do you have any update on the issue?, whatever you need don't hesitate to tell Us about it, regards

**Comment by mimisavage** [comment]
@sotoJ24 I will make a PR soon

**Comment by sotoJ24** [comment]
@mimisavage Nice, thank you for informing us
