### ISSUE TITLE
Verify email code mutation

### ISSUE THREAD

**Issue by rvalenciano** [safetrustcr/Frontend#94]
Create GraphQL operations to handle email verification code validation and resending.
Problem

Leverage this [PR](https://github.com/safetrustcr/Frontend/issues/75) to create the actual mutation for the backend.

We need to:

Validate the 6-digit verification code
Allow resending of verification code
Update user verification status

### Possible Solution

GraphQL Operations

````
mutation VerifyEmailCode($code: String!, $email: String!) {
  verify_email_code(code: $code, email: $email) {
    success
    message
  }
}

# Resend verification code mutation
mutation ResendVerificationCode($email: String!) {
  resend_verification_code(email: $email) {
    success
    message
  }
}

# Check verification status query
query CheckVerificationStatus($email: String!) {
  users(where: {email: {_eq: $email}}) {
    id
    is_verified
  }
}
```

**Comment by OWK50GA** [comment]
Can I handle this task?

**Comment by amJoe-dev** [comment]
hello, can i be assigned this issue, ill love to make it my first contribution to the community?

**Comment by Jagadeeshftw** [comment]
Can I take this issue?

**Comment by 0xdevcollins** [comment]
I'd like to handle this task.

**Comment by martinvibes** [comment]
hey sir i would like to work on this issue 
i'm a frontend dev, blockchain dev
kindly assign and i would get to work right away

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by 3th-Enjay** [comment]
Mind if I take this issue?

**Comment by sotoJ24** [comment]
> Can I take care of this issue?

Hi Dear @ikemHood how do you plan to solve the issue ?

**Comment by sotoJ24** [comment]
Remember guys, please mention how you plan to solve the issue

**Comment by Shalomnze** [comment]
i'll love to contribute to this project my ETA would be 24hrs after that i am sure you would be pleased with my work

**Comment by System625** [comment]
Hello good day , i am Olamiposi and i would love to work on this issue

i have experience in frontend development and integration, and i would love to work on this task as my first issue. So excited :)

I'll make sure the email validation and verification works without any hassle

my ETA is >24 hours

**Comment by Aditya-040** [comment]
I’d like to resolve this.

**Comment by olisaagbafor** [comment]
Could I take over this issue?

**Comment by emarc99** [comment]
Can I contribute to this one? First time here.

**Comment by Josue19-08** [comment]
Hi, I'm Josué, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way.

I'd love to work on this!

**Comment by emmz3230** [comment]
Mind if I try this one?
i am frontend web developer 
will love to use my skill on this issue to check the 6 digit email verification

**Comment by DotworldX** [comment]
I’d like to work on this.

**Comment by CEOliam** [comment]
Could I try solving this?

**Comment by mimisavage** [comment]
I'd like to handle this task.

**Comment by Yunusabdul38** [comment]
Is it okay if I tackle this?
